version: "3.9"

services:
  siembra-service:
    container_name: siembra-service
    build: .
    ports:
      - "8002:8000"
    env_file:
      - .env
    networks:
      - siembra-net
    # Para desarrollo:
    # volumes:
    #   - .:/app

networks:
  siembra-net:
    driver: bridge
