services:
  siembra-service:
    container_name: siembra-service
    build: .
    ports:
      - "8002:8000"
    env_file: .env
    volumes:
      - .:/app
    networks:
      - agrosavia-network

networks:
  agrosavia-network:
    external: true

