services:
  siembra-service:
    container_name: siembra-service
    build: .
    ports:
      - "8002:8000"
    env_file:
      - .env
    networks:
      - agrosavia-network
    restart: always
    # Para desarrollo:
    # volumes:
    #   - .:/app

networks:
  agrosavia-network:
    external: true
